# Generated by Django 5.2.1 on 2026-04-16 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundamentals', '0001_initial'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('period_type', models.CharField(max_length=16)),
                ('metric_code', models.CharField(max_length=64)),
                ('metric_name', models.CharField(max_length=128)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('unit', models.CharField(default='number', max_length=32)),
                ('calculation_version', models.CharField(default='v1', max_length=64)),
                ('source_trace', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computed_metric_snapshots', to='market_data.company')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computed_metric_snapshots', to='fundamentals.companyfinancialperiod')),
            ],
            options={
                'ordering': ['company', 'metric_code', '-as_of_date'],
                'indexes': [models.Index(fields=['company', 'metric_code', '-as_of_date'], name='analytics_c_company_e5d712_idx'), models.Index(fields=['company', 'period'], name='analytics_c_company_b58a45_idx'), models.Index(fields=['metric_code', 'period_type'], name='analytics_c_metric__4ffc54_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'period', 'metric_code', 'calculation_version'), name='uq_computed_metric_company_period_code_version')],
            },
        ),
        migrations.CreateModel(
            name='ValuationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('valuation_model', models.CharField(max_length=64)),
                ('scenario_name', models.CharField(default='base', max_length=64)),
                ('calculation_version', models.CharField(default='v1', max_length=64)),
                ('enterprise_value', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('equity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('implied_share_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('upside_downside_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('assumptions_json', models.JSONField(blank=True, default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('source_trace', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_snapshots', to='market_data.company')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_snapshots', to='fundamentals.companyfinancialperiod')),
            ],
            options={
                'ordering': ['company', '-as_of_date', 'valuation_model', 'scenario_name'],
                'indexes': [models.Index(fields=['company', '-as_of_date'], name='analytics_v_company_abc38a_idx'), models.Index(fields=['valuation_model', 'scenario_name'], name='analytics_v_valuati_46c672_idx'), models.Index(fields=['company', 'period'], name='analytics_v_company_64ecf6_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'period', 'valuation_model', 'scenario_name', 'calculation_version'), name='uq_valuation_company_period_model_scenario_version')],
            },
        ),
    ]
