# Generated by Django 5.2.1 on 2026-04-16 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=32, unique=True)),
                ('finnhub_symbol', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('currency_code', models.CharField(blank=True, max_length=16)),
                ('exchange', models.CharField(blank=True, max_length=128)),
                ('primary_exchange', models.CharField(blank=True, max_length=128)),
                ('ipo_date', models.DateField(blank=True, null=True)),
                ('market_identifier_code', models.CharField(blank=True, max_length=32)),
                ('logo_url', models.URLField(blank=True)),
                ('web_url', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
                'indexes': [models.Index(fields=['ticker'], name='market_data_ticker_2eb95a_idx'), models.Index(fields=['finnhub_symbol'], name='market_data_finnhub_31f1f3_idx'), models.Index(fields=['name'], name='market_data_name_56f1ad_idx'), models.Index(fields=['is_active'], name='market_data_is_acti_238a26_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyBasicMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(default='finnhub', max_length=64)),
                ('endpoint_name', models.CharField(default='basic_financials', max_length=128)),
                ('fetched_at', models.DateTimeField()),
                ('is_latest', models.BooleanField(db_index=True, default=False)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('metric_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_metric_snapshots', to='market_data.company')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['company', '-fetched_at'], name='market_data_company_e53bd1_idx'), models.Index(fields=['symbol', '-fetched_at'], name='market_data_symbol_d10a46_idx'), models.Index(fields=['source_name', 'endpoint_name'], name='market_data_source__02ba1d_idx'), models.Index(fields=['is_latest'], name='market_data_is_late_f85ffd_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'fetched_at', 'endpoint_name'), name='uq_basic_metric_snapshot_company_fetched_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfileSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(default='finnhub', max_length=64)),
                ('endpoint_name', models.CharField(default='company_profile', max_length=128)),
                ('fetched_at', models.DateTimeField()),
                ('is_latest', models.BooleanField(db_index=True, default=False)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('currency_code', models.CharField(blank=True, max_length=16)),
                ('exchange', models.CharField(blank=True, max_length=128)),
                ('ipo_date', models.DateField(blank=True, null=True)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('share_outstanding', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('ticker', models.CharField(blank=True, max_length=32)),
                ('web_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshots', to='market_data.company')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['company', '-fetched_at'], name='market_data_company_8de5c5_idx'), models.Index(fields=['symbol', '-fetched_at'], name='market_data_symbol_20322d_idx'), models.Index(fields=['source_name', 'endpoint_name'], name='market_data_source__d26ae6_idx'), models.Index(fields=['is_latest'], name='market_data_is_late_85ab1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'fetched_at', 'endpoint_name'), name='uq_profile_snapshot_company_fetched_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='CompanyQuoteSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(default='finnhub', max_length=64)),
                ('endpoint_name', models.CharField(default='quote', max_length=128)),
                ('fetched_at', models.DateTimeField()),
                ('is_latest', models.BooleanField(db_index=True, default=False)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('current_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('previous_close_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('quote_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_snapshots', to='market_data.company')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['company', '-fetched_at'], name='market_data_company_fb0cf1_idx'), models.Index(fields=['symbol', '-fetched_at'], name='market_data_symbol_8bb3e7_idx'), models.Index(fields=['quote_timestamp'], name='market_data_quote_t_8a0137_idx'), models.Index(fields=['is_latest'], name='market_data_is_late_f8c332_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'fetched_at', 'endpoint_name'), name='uq_quote_snapshot_company_fetched_endpoint')],
            },
        ),
    ]
