# Generated by Django 5.2.1 on 2026-04-16 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('error', 'Error')], default='active', max_length=32)),
                ('user_identifier', models.CharField(blank=True, max_length=128)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='chat_sessions', to='market_data.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField()),
                ('message_index', models.PositiveIntegerField()),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('token_usage_input', models.PositiveIntegerField(blank=True, null=True)),
                ('token_usage_output', models.PositiveIntegerField(blank=True, null=True)),
                ('grounding_json', models.JSONField(blank=True, default=dict)),
                ('tool_name', models.CharField(blank=True, max_length=128)),
                ('tool_arguments_json', models.JSONField(blank=True, default=dict)),
                ('source_trace', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession')),
            ],
            options={
                'ordering': ['session', 'message_index'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status', '-updated_at'], name='ai_assistan_status_1bbe97_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user_identifier'], name='ai_assistan_user_id_017f16_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['last_message_at'], name='ai_assistan_last_me_a7b056_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'message_index'], name='ai_assistan_session_b1c907_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='ai_assistan_role_f242d3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='ai_assistan_created_817c4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('session', 'message_index'), name='uq_chat_message_session_index'),
        ),
    ]
