# Generated by Django 5.2.1 on 2026-04-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backtestpricebar',
            new_name='backtesting_company_222109_idx',
            old_name='backtest_pr_company_583977_idx',
        ),
        migrations.RenameIndex(
            model_name='backtestpricebar',
            new_name='backtesting_symbol_fac33e_idx',
            old_name='backtest_pr_symbol_355177_idx',
        ),
        migrations.RenameIndex(
            model_name='backtestrun',
            new_name='backtesting_company_937bec_idx',
            old_name='backtest_ba_company_9c1654_idx',
        ),
        migrations.RenameIndex(
            model_name='backtestrun',
            new_name='backtesting_status_09349e_idx',
            old_name='backtest_ba_status_14740a_idx',
        ),
        migrations.RenameIndex(
            model_name='backtestrun',
            new_name='backtesting_strateg_615155_idx',
            old_name='backtest_ba_strateg_7d7594_idx',
        ),
        migrations.RenameIndex(
            model_name='strategyconfig',
            new_name='backtesting_strateg_b75eb1_idx',
            old_name='backtest_st_strateg_4ce0f0_idx',
        ),
    ]
