# Generated by Django 5.2.1 on 2026-04-16 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('company_sync', 'Company Sync'), ('financial_ingestion', 'Financial Ingestion'), ('analytics_compute', 'Analytics Compute'), ('valuation', 'Valuation'), ('chat_analysis', 'Chat Analysis'), ('report_generation', 'Report Generation')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('request_payload_json', models.JSONField(blank=True, default=dict)),
                ('result_payload_json', models.JSONField(blank=True, default=dict)),
                ('error_payload_json', models.JSONField(blank=True, default=dict)),
                ('requested_by', models.CharField(blank=True, max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_runs', to='market_data.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', 'status'], name='jobs_jobrun_job_typ_b649ca_idx'), models.Index(fields=['company', '-created_at'], name='jobs_jobrun_company_166595_idx'), models.Index(fields=['requested_by'], name='jobs_jobrun_request_71c491_idx'), models.Index(fields=['celery_task_id'], name='jobs_jobrun_celery__f85896_idx'), models.Index(fields=['idempotency_key'], name='jobs_jobrun_idempot_240991_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('job_type', 'idempotency_key'), name='uq_jobrun_jobtype_idempotency_nonempty')],
            },
        ),
    ]
