# Generated by Django 5.2.1 on 2026-04-16 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinancialPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=16)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('fiscal_quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('period_end_date', models.DateField()),
                ('currency_code', models.CharField(max_length=16)),
                ('source_name', models.CharField(default='finnhub', max_length=64)),
                ('source_period_key', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_periods', to='market_data.company')),
                ('source_basic_metric_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_periods', to='market_data.companybasicmetricsnapshot')),
                ('source_profile_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_periods', to='market_data.companyprofilesnapshot')),
            ],
            options={
                'ordering': ['company', '-period_end_date'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(default='finnhub', max_length=64)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
                ('net_income', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('depreciation_and_amortization', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('stock_based_compensation', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('changes_in_working_capital', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('cash_from_operating_activities', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('capital_expenditure', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('acquisitions', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('cash_from_investing_activities', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('debt_issued_or_repaid_net', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('dividends_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('share_repurchases', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('cash_from_financing_activities', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('net_change_in_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('free_cash_flow', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_statements', to='market_data.company')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_statement', to='fundamentals.companyfinancialperiod')),
            ],
            options={
                'ordering': ['company', '-period__period_end_date'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(default='finnhub', max_length=64)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
                ('cash_and_cash_equivalents', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('short_term_investments', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('accounts_receivable', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('inventory', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('other_current_assets', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('total_current_assets', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('property_plant_and_equipment', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('goodwill', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('intangible_assets', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('total_non_current_assets', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('accounts_payable', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('short_term_debt', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('other_current_liabilities', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('total_current_liabilities', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('long_term_debt', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('total_non_current_liabilities', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('retained_earnings', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('total_shareholders_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('total_liabilities_and_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='market_data.company')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet', to='fundamentals.companyfinancialperiod')),
            ],
            options={
                'ordering': ['company', '-period__period_end_date'],
            },
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(default='finnhub', max_length=64)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
                ('revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('cost_of_revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('operating_expense', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('selling_general_and_administrative', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('research_and_development', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('depreciation_and_amortization', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('operating_income', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('interest_expense', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('pretax_income', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('income_tax_expense', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('diluted_eps', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('weighted_average_diluted_shares', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_statements', to='market_data.company')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_statement', to='fundamentals.companyfinancialperiod')),
            ],
            options={
                'ordering': ['company', '-period__period_end_date'],
            },
        ),
        migrations.AddIndex(
            model_name='companyfinancialperiod',
            index=models.Index(fields=['company', 'period_type', '-period_end_date'], name='fundamental_company_96229a_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfinancialperiod',
            index=models.Index(fields=['company', 'fiscal_year', 'fiscal_quarter'], name='fundamental_company_21aea2_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfinancialperiod',
            index=models.Index(fields=['period_type', 'period_end_date'], name='fundamental_period__440eef_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyfinancialperiod',
            constraint=models.UniqueConstraint(fields=('company', 'period_type', 'fiscal_year', 'fiscal_quarter', 'period_end_date'), name='uq_financial_period_company_period_unique'),
        ),
        migrations.AddIndex(
            model_name='cashflowstatement',
            index=models.Index(fields=['company', 'period'], name='fundamental_company_4939b2_idx'),
        ),
        migrations.AddIndex(
            model_name='balancesheet',
            index=models.Index(fields=['company', 'period'], name='fundamental_company_833f08_idx'),
        ),
        migrations.AddIndex(
            model_name='incomestatement',
            index=models.Index(fields=['company', 'period'], name='fundamental_company_5b8b42_idx'),
        ),
    ]
