from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from unittest.mock import patch

from django.test import TestCase, override_settings

from apps.market_data.clients.finnhub import (
    FinnhubClient,
    FinnhubMissingAPIKeyError,
)
from apps.market_data.models import (
    Company,
    CompanyBasicMetricSnapshot,
    CompanyProfileSnapshot,
    CompanyQuoteSnapshot,
)
from apps.market_data.services import CompanyIngestionService


def sample_profile_payload(symbol: str = "AAPL") -> dict:
    return {
        "country": "US",
        "currency": "USD",
        "exchange": "NASDAQ",
        "ipo": "1980-12-12",
        "marketCapitalization": 3000000.0,
        "name": "Apple Inc",
        "phone": "123456789",
        "shareOutstanding": 15000.0,
        "ticker": symbol,
        "weburl": "https://www.apple.com",
        "logo": "https://logo.example/aapl.png",
        "finnhubIndustry": "Technology",
    }


def sample_quote_payload() -> dict:
    return {
        "c": 190.25,
        "d": 1.25,
        "dp": 0.66,
        "h": 191.00,
        "l": 188.50,
        "o": 189.00,
        "pc": 189.00,
        "t": 1735689600,
    }


def sample_basic_payload() -> dict:
    return {
        "metric": {
            "peTTM": 28.2,
            "pbQuarterly": 35.5,
            "52WeekHigh": 199.62,
        }
    }


def sample_financials_payload(symbol: str = "AAPL") -> dict:
    return {
        "cik": "320193",
        "symbol": symbol,
        "data": [
            {
                "accessNumber": "0000320193-25-000079",
                "symbol": symbol,
                "cik": "320193",
                "year": 2025,
                "quarter": 0,
                "form": "10-K",
                "startDate": "2024-09-29 00:00:00",
                "endDate": "2025-09-27 00:00:00",
                "filedDate": "2025-10-31 00:00:00",
                "acceptedDate": "2025-10-31 06:01:26",
                "report": {
                    "bs": [
                        {"concept": "us-gaap_CashAndCashEquivalentsAtCarryingValue", "label": "Cash and cash equivalents", "unit": "usd", "value": 35934000000.0},
                        {"concept": "us-gaap_MarketableSecuritiesCurrent", "label": "Marketable securities", "unit": "usd", "value": 18763000000.0},
                        {"concept": "us-gaap_AccountsReceivableNetCurrent", "label": "Accounts receivable, net", "unit": "usd", "value": 39777000000.0},
                        {"concept": "us-gaap_InventoryNet", "label": "Inventories", "unit": "usd", "value": 5718000000.0},
                        {"concept": "us-gaap_Assets", "label": "Total assets", "unit": "usd", "value": 364980000000.0},
                        {"concept": "us-gaap_Liabilities", "label": "Total liabilities", "unit": "usd", "value": 290000000000.0},
                        {"concept": "us-gaap_StockholdersEquity", "label": "Total shareholders' equity", "unit": "usd", "value": 74980000000.0},
                        {"concept": "us-gaap_LiabilitiesCurrent", "label": "Current liabilities", "unit": "usd", "value": 140000000000.0},
                    ],
                    "ic": [
                        {"concept": "us-gaap_RevenueFromContractWithCustomerExcludingAssessedTax", "label": "Net sales", "unit": "usd", "value": 416161000000.0},
                        {"concept": "us-gaap_CostOfGoodsAndServicesSold", "label": "Cost of sales", "unit": "usd", "value": 220960000000.0},
                        {"concept": "us-gaap_GrossProfit", "label": "Gross margin", "unit": "usd", "value": 195201000000.0},
                        {"concept": "us-gaap_OperatingIncomeLoss", "label": "Operating income", "unit": "usd", "value": 123216000000.0},
                        {"concept": "us-gaap_NetIncomeLoss", "label": "Net income", "unit": "usd", "value": 112010000000.0},
                        {"concept": "us-gaap_EarningsPerShareDiluted", "label": "Diluted EPS", "unit": "usd", "value": 7.5},
                        {"concept": "us-gaap_WeightedAverageNumberOfDilutedSharesOutstanding", "label": "Diluted shares", "unit": "shares", "value": 14934000000.0},
                    ],
                    "cf": [
                        {"concept": "us-gaap_NetIncomeLoss", "label": "Net income", "unit": "usd", "value": 112010000000.0},
                        {"concept": "us-gaap_DepreciationDepletionAndAmortization", "label": "Depreciation and amortization", "unit": "usd", "value": 11698000000.0},
                        {"concept": "us-gaap_ShareBasedCompensation", "label": "Share-based compensation expense", "unit": "usd", "value": 12863000000.0},
                        {"concept": "us-gaap_NetCashProvidedByUsedInOperatingActivities", "label": "Cash generated by operating activities", "unit": "usd", "value": 130000000000.0},
                        {"concept": "us-gaap_PaymentsToAcquirePropertyPlantAndEquipment", "label": "Capital expenditures", "unit": "usd", "value": -11000000000.0},
                    ],
                },
            }
        ],
    }


class FinnhubClientTests(TestCase):
    @override_settings(FINNHUB_API_KEY="")
    def test_missing_api_key_raises(self):
        with self.assertRaises(FinnhubMissingAPIKeyError):
            FinnhubClient()

    @override_settings(FINNHUB_API_KEY="test-key", FINNHUB_BASE_URL="https://example.com/api/v1")
    @patch("apps.market_data.clients.finnhub.requests.get")
    def test_get_company_profile_success(self, mock_get):
        class MockResponse:
            status_code = 200

            def json(self):
                return sample_profile_payload()

        mock_get.return_value = MockResponse()

        client = FinnhubClient()
        response = client.get_company_profile("AAPL")

        self.assertEqual(response.endpoint_name, "company_profile")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.payload["ticker"], "AAPL")


class CompanyIngestionServiceTests(TestCase):
    @patch("apps.market_data.services.FinnhubClient")
    def test_ingest_company_creates_records(self, mock_client_cls):
        mock_client = mock_client_cls.return_value

        mock_client.get_company_profile.return_value.endpoint_name = "company_profile"
        mock_client.get_company_profile.return_value.params = {"symbol": "AAPL"}
        mock_client.get_company_profile.return_value.status_code = 200
        mock_client.get_company_profile.return_value.payload = sample_profile_payload()

        mock_client.get_quote.return_value.endpoint_name = "quote"
        mock_client.get_quote.return_value.params = {"symbol": "AAPL"}
        mock_client.get_quote.return_value.status_code = 200
        mock_client.get_quote.return_value.payload = sample_quote_payload()

        mock_client.get_basic_financials.return_value.endpoint_name = "basic_financials"
        mock_client.get_basic_financials.return_value.params = {"symbol": "AAPL", "metric": "all"}
        mock_client.get_basic_financials.return_value.status_code = 200
        mock_client.get_basic_financials.return_value.payload = sample_basic_payload()

        mock_client.get_financials_reported.return_value.endpoint_name = "financials_reported"
        mock_client.get_financials_reported.return_value.params = {"symbol": "AAPL"}
        mock_client.get_financials_reported.return_value.status_code = 200
        mock_client.get_financials_reported.return_value.payload = sample_financials_payload()

        service = CompanyIngestionService(client=mock_client)
        result = service.ingest_company("AAPL", ingest_statements=True)

        self.assertEqual(result.ticker, "AAPL")
        self.assertTrue(Company.objects.filter(ticker="AAPL").exists())
        self.assertEqual(CompanyProfileSnapshot.objects.count(), 1)
        self.assertEqual(CompanyQuoteSnapshot.objects.count(), 1)
        self.assertEqual(CompanyBasicMetricSnapshot.objects.count(), 1)

        company = Company.objects.get(ticker="AAPL")
        self.assertEqual(company.financial_periods.count(), 1)
        self.assertEqual(company.income_statements.count(), 1)
        self.assertEqual(company.balance_sheets.count(), 1)
        self.assertEqual(company.cash_flow_statements.count(), 1)

    @patch("apps.market_data.services.FinnhubClient")
    def test_ingest_company_is_idempotent_for_identical_snapshots(self, mock_client_cls):
        mock_client = mock_client_cls.return_value

        mock_client.get_company_profile.return_value.endpoint_name = "company_profile"
        mock_client.get_company_profile.return_value.params = {"symbol": "AAPL"}
        mock_client.get_company_profile.return_value.status_code = 200
        mock_client.get_company_profile.return_value.payload = sample_profile_payload()

        mock_client.get_quote.return_value.endpoint_name = "quote"
        mock_client.get_quote.return_value.params = {"symbol": "AAPL"}
        mock_client.get_quote.return_value.status_code = 200
        mock_client.get_quote.return_value.payload = sample_quote_payload()

        mock_client.get_basic_financials.return_value.endpoint_name = "basic_financials"
        mock_client.get_basic_financials.return_value.params = {"symbol": "AAPL", "metric": "all"}
        mock_client.get_basic_financials.return_value.status_code = 200
        mock_client.get_basic_financials.return_value.payload = sample_basic_payload()

        mock_client.get_financials_reported.return_value.endpoint_name = "financials_reported"
        mock_client.get_financials_reported.return_value.params = {"symbol": "AAPL"}
        mock_client.get_financials_reported.return_value.status_code = 200
        mock_client.get_financials_reported.return_value.payload = sample_financials_payload()

        service = CompanyIngestionService(client=mock_client)
        service.ingest_company("AAPL", ingest_statements=True)
        service.ingest_company("AAPL", ingest_statements=True)

        self.assertEqual(CompanyProfileSnapshot.objects.count(), 1)
        self.assertEqual(CompanyQuoteSnapshot.objects.count(), 1)
        self.assertEqual(CompanyBasicMetricSnapshot.objects.count(), 1)

        company = Company.objects.get(ticker="AAPL")
        self.assertEqual(company.financial_periods.count(), 1)